path_poses:
# round 1
  - { x:  0, y: 0, yaw: 0 }
  - { x:  13, y: 0, yaw: -45 }
  - { x:  14.5, y: -1.5, yaw: -90 }
  - { x:  14.5, y: -11.5, yaw: -135 }
  - { x:  13, y: -13, yaw: -180 }
  - { x:  2.5, y: -13, yaw: 135 }
  - { x:  1, y: -11.5, yaw: 90 }
  - { x:  1, y: -3, yaw: 45 }
  #
  - { x:  2.5, y: -1.5, yaw: 0 }
  - { x:  11.5, y: -1.5, yaw: -45 }
  - { x:  13, y: -3, yaw: -90 }
  - { x:  13, y: -10, yaw: -135 }
  - { x:  11.5, y: -11.5, yaw: -180 }
  - { x:  4, y: -11.5, yaw: 135 }
  - { x:  2.5, y: -10, yaw: 90 }
  - { x:  2.5, y: -4.5, yaw: 45 }
  #
  - { x:  4, y: -3, yaw: 0 }
  - { x:  10, y: -3, yaw: -45 }
  - { x:  11.5, y: -4.5, yaw: -90 }
  - { x:  11.5, y: -8.5, yaw: -135 }
  - { x:  10, y: -10, yaw: -180 }
  - { x:  5.5, y: -10, yaw: 135 }
  - { x:  4, y: -8.5, yaw: 90 }
  - { x:  4, y: -6, yaw: 45 }
# round 2
  - { x:  4, y: -6, yaw: -135 }
  - { x:  4, y: -8.5, yaw: -90 }
  - { x:  5.5, y: -10, yaw: -45 }
  - { x:  10, y: -10, yaw: 0 }
  - { x:  11.5, y: -8.5, yaw: 45 }
  - { x:  11.5, y: -4.5, yaw: 90 }
  - { x:  10, y: -3, yaw: 135 }
  - { x:  4, y: -3, yaw: 180 }
  #
  - { x:  2.5, y: -4.5, yaw: -135 }
  - { x:  2.5, y: -10, yaw: -90 }
  - { x:  4, y: -11.5, yaw: -45 }
  - { x:  11.5, y: -11.5, yaw: 0 }
  - { x:  13, y: -10, yaw: 45 }
  - { x:  13, y: -3, yaw: 90 }
  - { x:  11.5, y: -1.5, yaw: 135 }
  - { x:  2.5, y: -1.5, yaw: 180 }
  #
  - { x:  1, y: -3, yaw: -135 }
  - { x:  1, y: -11.5, yaw: -90 }
  - { x:  2.5, y: -13, yaw: -45 }
  - { x:  13, y: -13, yaw: 0 }
  - { x:  14.5, y: -11.5, yaw: 45 }
  - { x:  14.5, y: -1.5, yaw: 90 }
  - { x:  13, y: 0, yaw: 135 }
  - { x:  0, y: 0, yaw: 180 }
 
