path_poses:

  - { x:  0, y: 0, yaw: 0 }
  - { x:  5, y: 0, yaw: 0 }
  - { x:  6.5, y: -1, yaw: -90 }
  # - { x:  7, y: -4, yaw: -30 }
  - { x:  5, y: -7, yaw: -180 }
  - { x:  0, y: -8, yaw: -90 }
  - { x:  7, y: -9.5, yaw: -60 }
  - { x:  9, y: -13, yaw: -30 }
  # - { x:  11, y: -10, yaw: 0 }
  # - { x:  13, y: -10, yaw: -45 }
  - { x:  17, y: -13.5, yaw: -60 }
