path_poses:

  # - { x:  0, y: 0, yaw: 0 }
  # - { x:  5, y: 0, yaw: 0 }
  # - { x:  6.5, y: -1, yaw: -90 }
  # - { x:  7.5, y: -5.5, yaw: 0 }
  # - { x:  14, y: -5.5, yaw: -30 }
  # - { x:  15, y: -6, yaw: -60 }
  # - { x:  15, y: -6.75, yaw: -120 }
  # - { x:  14, y: -7.5, yaw: -180 }
  # - { x:  7.5, y: -5.5, yaw: 90 }
  # - { x:  6.5, y: -1, yaw: 90 }
  # - { x:  5, y: 0, yaw: 180 }
  # - { x:  0, y: 0, yaw: 180 }

  # - { x:  0, y: 0, yaw: 0 }
  # - { x:  5, y: 0, yaw: 0 }
  # - { x:  6.5, y: -1, yaw: -90 }
  # - { x:  7.5, y: -5.5, yaw: 0 }
  # # - { x:  10, y: -6, yaw: -30 }
  # - { x:  14, y: -6.5, yaw: -70 }
  # - { x:  14.25, y: -6.9, yaw: -100 }
  # - { x:  14.25, y: -7.25, yaw: -130 }
  # - { x:  14.25, y: -7.6, yaw: -160 }
  # - { x:  14, y: -8, yaw: -180 }
  # - { x:  7.5, y: -6, yaw: 90 }
  # - { x:  6.5, y: -1, yaw: 90 }
  # - { x:  5, y: -0.5, yaw: 180 }
  # - { x:  0, y: 0, yaw: 180 }

  - { x:  0, y: 0, yaw: 0 }
  - { x:  5, y: 0, yaw: 0 }
  - { x:  6.5, y: -1, yaw: -90 }
  # - { x:  7, y: -4, yaw: -30 }
  - { x:  7.5, y: -5.5, yaw: 0 }
  - { x:  13.5, y: -6.5, yaw: -70 }
  - { x:  13.75, y: -6.9, yaw: -100 }
  - { x:  13.75, y: -7.25, yaw: -130 }
  - { x:  13.75, y: -7.6, yaw: -160 }
  - { x:  13.5, y: -8, yaw: -180 }
  - { x:  7.5, y: -6, yaw: 90 }
  - { x:  6.5, y: -1, yaw: 90 }
  - { x:  5, y: -0.5, yaw: 180 }
  - { x:  0, y: 0, yaw: 180 }