path_poses:
  - { x:  0, y: 0, yaw: 0 }
  - { x:  60, y: 0, yaw: 0 }
  - { x:  8, y: 1, yaw: -90 }
  - { x:  8, y: 6, yaw: -90 }
  - { x:  7, y: 7, yaw: -180 }
  - { x:  0.5, y: 7, yaw: -180 }
  - { x:  -0.5, y: 8, yaw: -90 }
  - { x:  0.5, y: 9, yaw: 0 }
  - { x:  6, y: 9, yaw: 0 }
  - { x:  7, y: 10, yaw: -90 }
  - { x:  8, y: 14, yaw: -45 }

  # - { x:  9, y: -5, yaw: 180 }
  # - { x:  3, y: -5, yaw: 180 }
  # - { x:  1, y: -4, yaw: 90 }
  # - { x:  1, y: 1, yaw: 90 }
  # - { x:  2, y: 2, yaw: 0 }
  # - { x:  8.5, y: 2, yaw: 0 }
  # - { x:  9.5, y: 3, yaw: 90 }
  # - { x:  8.5, y: 4, yaw: 180 }
  # - { x:  3, y: 4, yaw: 180 }
  # - { x:  2, y: 5, yaw: 90 }
  # - { x:  1, y: 9, yaw: 135 }
