path_poses:
# round 1
  - { x:  0, y: 0, yaw: 0 }
  - { x:  12, y: 0, yaw: -45 }
  - { x:  13.5, y: -1.5, yaw: -90 }
  - { x:  13.5, y: -11.5, yaw: -135 }
  - { x:  12, y: -13, yaw: -180 }
  - { x:  1.5, y: -13, yaw: 135 }
  - { x:  0, y: -11.5, yaw: 90 }
  - { x:  0, y: -1.5, yaw: 60 }
# round 2
  - { x:  1.5, y: 0, yaw: 15 }
  - { x:  12, y: 0, yaw: -45 }
  - { x:  13.5, y: -1.5, yaw: -90 }
  - { x:  13.5, y: -11.5, yaw: -135 }
  - { x:  12, y: -13, yaw: -180 }
  - { x:  1.5, y: -13, yaw: 135 }
  - { x:  0, y: -11.5, yaw: 90 }
  - { x:  0, y: 0, yaw: 90 }