path_poses:
  - { x:  0, y: 0, yaw: 0 }
  - { x:  3.12, y: 0, yaw: 0 }
  # - { x:  6.5, y: -1, yaw: -60 }
  - { x:  5, y: -1, yaw: 0 }
  # - { x:  7.0, y: -3.75, yaw: -140 }
  - { x:  12.36, y: -1, yaw: 0 }