path_poses:
  - { x:  0, y: 0, yaw: 0 }
  - { x:  7.0, y: -0.5, yaw: -40 }
  # - { x:  6.5, y: -1, yaw: -60 }
  - { x:  7.5, y: -3.5, yaw: -120 }
  # - { x:  7.0, y: -3.75, yaw: -140 }
  - { x:  2,   y: -4, yaw: -180 }

  # - { x:  0, y: 0, yaw: 0 }
  # - { x:  6.5, y: -2, yaw: -90 }
  # - { x:  2, y: -4, yaw: -180 }