path_poses:
  - { x:  0, y: 0, yaw: 0 }
  - { x:  6.0, y: -0.5, yaw: -40 }
  - { x:  6.5, y: -1, yaw: -60 }
  - { x:  6.0, y: -3.5, yaw: -140 }
  # - { x:  5, y: -5, yaw: -180 }
  # - { x:  1, y: -6, yaw: -180 }
  - { x:  2, y: -4, yaw: -180 }
