path_poses:
# section 1
# round 1~3
  - { x:  0, y: 0, yaw: 0 }
  - { x:  13.5, y: 0, yaw: 45 }
  - { x:  13.5, y: 2, yaw: 135 }
  - { x:  0, y: 2, yaw: -135 }
  - { x:  0, y: 0, yaw: -45 }
  #
  # - { x:  0, y: 0, yaw: 0 }
  # - { x:  13, y: 0, yaw: 45 }
  # - { x:  14.5, y: 1.5, yaw: 90 }
  # - { x:  14.5, y: 2.5, yaw: 135 }
  # - { x:  13, y: 4, yaw: 180 }
  # - { x:  1.5, y: 4, yaw: -135 }
  # - { x:  0, y: 2.5, yaw: -90 }
  # - { x:  0, y: 1.5, yaw: -45 }
  #
  - { x:  13.5, y: 0, yaw: 45 }
  - { x:  13.5, y: 2, yaw: 135 }
  - { x:  0, y: 2, yaw: -135 }
  - { x:  0, y: 0, yaw: -45 }
  #
  - { x:  0, y: -5, yaw: 0 }
# section 2
# round 1~3
  - { x:  13.5, y: -5, yaw: -45 }
  - { x:  13.5, y: -12, yaw: -135 }
  - { x:  1, y: -12, yaw: 135 }
  - { x:  1, y: -5, yaw: 45 }
  #
  - { x:  13.5, y: -5, yaw: -45 }
  - { x:  13.5, y: -12, yaw: -135 }
  - { x:  1, y: -12, yaw: 135 }
  - { x:  1, y: -5, yaw: 45 }
  #
  # - { x:  13.5, y: -5, yaw: -45 }
  # - { x:  13.5, y: -12, yaw: -135 }
  # - { x:  1, y: -12, yaw: 135 }
  # - { x:  0, y: 0, yaw: 90 }
#
  - { x:  13.5, y: 0, yaw: 45 }
  - { x:  13.5, y: 2, yaw: 135 }
  - { x:  0, y: 2, yaw: -135 }
  - { x:  0, y: 0, yaw: -90 }