path_poses:
# round 1
  - { x: 0, y: 0, yaw: 0 }
  - { x: 13.5, y: -2, yaw: -90 }
  - { x: 0, y: -4, yaw: -90 }
# round 2
  - { x: 13.5, y: -6, yaw: -90 }
  - { x: 0, y: -8, yaw: -90 }
# round 3
  - { x: 13.5, y: -10, yaw: -90 }
  - { x: 0, y: -12, yaw: -90 }
# return
  - { x: 1.5, y: -13.5, yaw: 0 }
  - { x: 6.5, y: -13.5, yaw: 90 }
  - { x: 0, y: 0, yaw: 90 }